versions: '3.8'

services:
    frontend: 
      image: baviske:/budget-app-backend:latest 
      container_name: frontend-app
      ports:
        - "80:80"
      environment:
        - NODE_ENV=production


